In [1]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[1, 0, 0],
					[0, 1, 0],
					[0, 0, 1]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nDeterminant of given 3X3 square matrix:")
print(int(det))


Numpy Matrix is:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Determinant of given 3X3 square matrix:
1


In [2]:
# importing Numpy package
import numpy as np

# creating a 2X2 Numpy matrix
n_array = np.array([[1, 0], [0, 1]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nDeterminant of given 2X2 matrix:")
print(int(det))


Numpy Matrix is:
[[1 0]
 [0 1]]

Determinant of given 2X2 matrix:
1


### Sifat 1 : determinan matrix identitas dengan ordo berapapun adalah 1

In [3]:
A = np.array([[1, 0, 0],
					[0, 1, 0],
					[0, 0, 1]])
print("Sifat 1 : determinan matrix identitas selalu 1")
print(A)
det = np.linalg.det(A)
print(int(det))

Sifat 1 : determinan matrix identitas selalu 1
[[1 0 0]
 [0 1 0]
 [0 0 1]]
1


### Sifat 2 : jika salah satu baris diubah nilai elemennya maka hasil determinannnya juga ikut berubah

In [4]:
c = np.array([[1, 2, 1],
					[3, 1, 2],
					[2, 1, 2]])
print(c)
det = np.linalg.det(c)
print(int(det))

[[1 2 1]
 [3 1 2]
 [2 1 2]]
-3


In [5]:
d = np.array([[3, 1, 2],
					[1, 2, 1],
					[2, 1, 2]])
print(c)
print("sifat 2 : merubah baris dapat mengubah hasil determinan")
det = np.linalg.det(d)
print(int(det))

[[1 2 1]
 [3 1 2]
 [2 1 2]]
sifat 2 : merubah baris dapat mengubah hasil determinan
3


### Sifat 3 : Jika suatu baris ataupun kolom merupakan kelipatan dari baris atau kolom yang lain maka determinan matrix tersebut adalah 0 (baris 2 adalah kelipatan dari baris 1)

In [6]:
e = np.array([[1, 2, 1],
					[2, 4, 2],
					[2, 1, 2]])
print(c)
print("sifat 3 : Jika suatu baris adalah kelipatan dari baris yang lain maka determinan matrix tersebut adalah 0")
det = np.linalg.det(e)
print(int(det))

[[1 2 1]
 [3 1 2]
 [2 1 2]]
sifat 3 : Jika suatu baris adalah kelipatan dari baris yang lain maka determinan matrix tersebut adalah 0
0


In [7]:
f = np.array([[1, 2, 1],
					[2, 4, 2],
					[2, 4, 3]])
print(c)
print("sifat 3 : Jika suatu kolom adalah kelipatan dari kolom yang lain maka determinan matrix tersebut adalah 0")
det = np.linalg.det(f)
print(int(det))

[[1 2 1]
 [3 1 2]
 [2 1 2]]
sifat 3 : Jika suatu kolom adalah kelipatan dari kolom yang lain maka determinan matrix tersebut adalah 0
0


### sifat 4 : Jika matrix tersebut adalah kelipatan sebanyak n * matrix maka untuk mencari determinan adalah (n^(sebanyak ordo)determinan matrix)contoh matrix g adalah kelipatan 2 kali dari matrix d : (2^3(det d))

In [8]:
g = np.array([[6, 2, 4],
					[2, 4, 2],
					[4, 2, 4]])
print(g)
print("sifat 4 : Jika Matrix tersebut adalah kelipatan 2 x matrix d maka dapat disimpulkan (2^3(det d))")
det = np.linalg.det(g)
print(int(det))

[[6 2 4]
 [2 4 2]
 [4 2 4]]
sifat 4 : Jika Matrix tersebut adalah kelipatan 2 x matrix d maka dapat disimpulkan (2^3(det d))
24


#### Contoh dengan ordo 2x2
matrix h adalah kelipatan 2x matrix a jadi (2^2(det a)) = -20

In [9]:
a = np.array([[3, 4],
					[2, 1]])
print(a)
# print("sifat 4 : Jika suatu kolom adalah kelipatan dari kolom yang lain maka determinan matrix tersebut adalah 0")
det = np.linalg.det(a)
print(det.round())

[[3 4]
 [2 1]]
-5.0


In [10]:
h = np.array([[6, 8],
					[4, 2]])
print(h)
print("sifat 4 : Jika suatu kolom adalah kelipatan dari kolom yang lain maka determinan matrix tersebut adalah 0")
det = np.linalg.det(h)
print(det.round())

[[6 8]
 [4 2]]
sifat 4 : Jika suatu kolom adalah kelipatan dari kolom yang lain maka determinan matrix tersebut adalah 0
-20.0


### Sifat 5 : Jika terdapat matrix baru dengan nilai salah satu baris atau kolom adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2*(determinan matrix)
contoh matrix i baris pertama adalah kelipatan 2 dari matrix a
contoh matrix j kolom pertama adalah kelipatan 2 dari matrix a

In [11]:
i = np.array([[6, 8],
					[2, 1]])
print(i)
print("sifat 5 : jika terdapat matrix baru dengan nilai salah satu baris adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2x(det a)")
det = np.linalg.det(i)
print(det.round())

[[6 8]
 [2 1]]
sifat 5 : jika terdapat matrix baru dengan nilai salah satu baris adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2x(det a)
-10.0


In [12]:
j = np.array([[6, 4],
					[4, 1]])
print(j)
print("sifat 5 : jika terdapat matrix baru dengan nilai salah satu kolom adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2x(det a)")
det = np.linalg.det(j)
print(det.round())

[[6 4]
 [4 1]]
sifat 5 : jika terdapat matrix baru dengan nilai salah satu kolom adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2x(det a)
-10.0


### Sifat 6 : Jika suatu matrix yang berasal dari penjumlahan matrix k dengan matrix a maka untuk mencari determinan cukup menjumlahkan hasil dari 2 determinan matrix tersebut

In [13]:
k = np.array([[4, 1],
					[2, 1]])
print(k)

det = np.linalg.det(k)
print(det.round())

[[4 1]
 [2 1]]
2.0


In [14]:
a = np.array([[3, 4],
					[2, 1]])
print(a)

det = np.linalg.det(a)
print(det.round())

[[3 4]
 [2 1]]
-5.0


In [15]:
l = np.array([[7, 5],
					[2, 1]])
print(l)
print("2+(-5)=-3")
det = np.linalg.det(l)
print(det.round())

[[7 5]
 [2 1]]
2+(-5)=-3
-3.0


### Sifat 7 : Jika ada matrix segitiga atas atau bawah maka determinan nya adalah perkalian anggota diagonal matrix tersebut

In [16]:
m = np.array([[1, 2, 3],
					[0, 2, 1],
					[0, 0, 2]])

print(m)
det = np.linalg.det(m)
print(int(det))

[[1 2 3]
 [0 2 1]
 [0 0 2]]
4


In [17]:
n = np.array([[2, 0, 0],
					[3, 3, 0],
					[1, 2, 2]])

print(n)
det = np.linalg.det(n)
print(int(det))

[[2 0 0]
 [3 3 0]
 [1 2 2]]
12


### Sifat 8 : untuk mencari determinan dari Hasil perkalian matrix O dengan matrix p yaitu dengan mengalikan determinan matrix O dan p contoh (det O = 1 , det p = 1 maka det q adalah 0)

In [18]:
O = np.array([[2, 1],
					[1, 1]])

print(O)
det = np.linalg.det(O)
print(int(det))

[[2 1]
 [1 1]]
1


In [19]:
p = np.array([[1, 1],
					[1, 1]])

print(p)
det = np.linalg.det(p)
print(int(det))

[[1 1]
 [1 1]]
0


In [20]:
q=O@p
print(q)
det = np.linalg.det(q)
print(int(det))

[[3 3]
 [2 2]]
0
