# Matrix Invers
Invers matriks adalah kebalikan (invers) dari sebuah matriks yang apabila matriks tersebut dikalikan dengan inversnya, akan menjadi matriks identitas. Invers matriks dilambangkan dengan A-1. Suatu matriks dikatakan memiliki invers jika determinan dari matriks tersebut tidak sama dengan nol.

Contoh : Matriks A dengan ordo 2 x 2
$$
A=\begin{bmatrix}
a & b\\
c & d
\end{bmatrix}
$$

maka
$$
A^{-1} = \frac{1}{\det{\left(A\right)}} \left[\begin{matrix}d&-b\\-c&a\\\end{matrix}\right]$$

$$A^{-1} = \frac{1}{ad-bc} \left[\begin{matrix}d&-b\\-c&a\\\end{matrix}\right]$$



## Sifat sifat Matrix
$(A^{-1})^{-1} = A$

$A^n$ invertibel dan $(A^n)^{-1} = (A^{-1})^n$

$kA$ adalah matriks invertibel dan $(kA)^{-1} = (\frac{1}{k})A^{-1}$

$A^T$ invertibel dan $(A^T)^{-1} = (A^{-1})^T$

$A$ dan $B$ keduanya matriks invertibel, maka $AB$ invertibel dan $(AB)^{-1} = B^{-1}A^{-1}$

## Mencari matriks invers dengan eliminasi gauss jordan

Contoh mencari invers dengan eliminasi gauss jordan menggunakan matriks dengan ordo 3x3

Contoh soal $$A = \begin{bmatrix}
1 & 2 &3\\
0 & 1 & 4 \\
5 & 6 & 0
\end{bmatrix}$$

$$I = \begin{bmatrix}
1 & 0 &0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}$$

Kemudian gunakan gauss jordan elimination
$$A = \begin{bmatrix}
1 & 2 &3|1 & 0 &0\\
0 & 1 & 4|0 & 1 & 0  \\
5 & 6 & 0|0 & 0 & 1
\end{bmatrix}$$

untuk mencari invers, gimana caranya matriks identitasnya bisa ada disebelah kiri, terserah baris berapa mau di tambahin/dikurangin/dikali/dibagi dengan baris manapun.

Kita kalikan baris pertama dengan 5 kemudian dikurangi baris ketiga
$$A = \begin{bmatrix}
1 & 2 &3|1 & 0 &0\\
0 & 1 & 4|0 & 1 & 0  \\
0 & -4 & -15|-5 & 0 & 1
\end{bmatrix}$$

dari matriks diatas, kita tambahkan baris ke tiga dengan 4 kali baris kedua
$$A = \begin{bmatrix}
1 & 2 &3|1 & 0 &0\\
0 & 1 & 4|0 & 1 & 0  \\
0 & 0 & 1|-5 & 4 & 1
\end{bmatrix}$$

selanjutnya kita kurangkan baris kedua dengan 4 kali baris ketiga
dan kita kurangkan juga baris pertama dengan 3 kali baris ketiga
$$A = \begin{bmatrix}
1 & 2 &0|16 & -12 & -3\\
0 & 1 & 0|20 & -15 & -4  \\
0 & 0 & 1|-5 & 4 & 1
\end{bmatrix}$$

langkah terakhir kita tinggal kurangkan baris pertama dengan 2x baris kedua.hasilnya :
$$A = \begin{bmatrix}
1 & 0 &0|-24 & 18 & 5\\
0 & 1 & 0|20 & -15 & -4  \\
0 & 0 & 1|-5 & 4 & 1
\end{bmatrix}$$

nah yang ada disebelah kanan adalah invers dari matrik A.
jadi invers matriknya

$$A^{-1} = \begin{bmatrix}
-24 & 18 & 5\\
20 & -15 & -4  \\
-5 & 4 & 1
\end{bmatrix}$$


In [1]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
a = np.array([[1,2,3,1,0,0],[0,1,4,0,1,0],[5,6,0,0,0,1]])
print(a)

[[1 2 3 1 0 0]
 [0 1 4 0 1 0]
 [5 6 0 0 0 1]]


In [3]:
b = RowAdd(a,0,2,-5)
print(b)

[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]


In [4]:
c = RowAdd(b,1,2,4)
print(c)

[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]


In [5]:
d = RowAdd(c,2,1,-4)
print(d)

[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


In [6]:
e = RowAdd(d,2,0,-3)
print(e)

[[  1.   2.   0.  16. -12.  -3.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


In [7]:
f = RowAdd(e,1,0,-2)
print(f)

[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


In [8]:
g = np.array([[-24,18,5],[20,-15,-4],[-5,4,1]])
print(g)

[[-24  18   5]
 [ 20 -15  -4]
 [ -5   4   1]]


## Solusi persamaan linear dengan persaamaan invers


$2x+3y=6$

$4x+5y=11$

Dalam persamaan matrik

$$
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
6\\
11
\end{bmatrix}
$$

Solusi Persamaan linier

$$
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}^{-1}
\begin{bmatrix}
6\\
11
\end{bmatrix}
$$

Lakukan invers

$$
=\frac{1}{-2}\begin{bmatrix}
5 & -3\\
-4 & 2
\end{bmatrix}
\begin{bmatrix}
6\\
11
\end{bmatrix}
$$

Kalikan Matrix

$$
=\frac{1}{-2}\begin{bmatrix}
-3\\
-2
\end{bmatrix}
$$

$$
\begin{bmatrix}
1.5\\
1
\end{bmatrix}
$$

In [9]:
import numpy as np
a = np.array([[2, 3], [4, 5]])
b = np.array([[6], [11]])
q = np.linalg.solve(a, b)
print(q)

[[1.5]
 [1. ]]


## Membuat soal persamaan linear 6 variable


Soal :

\begin{align*}
x_1+x_2+x_3+2x_4+x_5+2x_6&=14\\
2x_1+3x_2+x_3+x_4+4x_5+2x_6&=23\\
x_1+3x_2+2x_3+2x_4+4x_5+x_6&=21\\
x_1+x_2+x_3+x_4+x_5+x_6&=11\\
3x_1+3x_2+3x_3+2x_4+4x_5+x_6&=29\\
2x_1+x_2+3x_3+2x_4+4x_5+x_6&=22
\end{align*}

In [10]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [11]:
a = np.array([[1,1,1,2,1,2,1,0,0,0,0,0],[2,3,1,1,4,2,0,1,0,0,0,0],[1,3,2,2,4,1,0,0,1,0,0,0],[1,1,1,1,1,1,0,0,0,1,0,0],[3,3,3,2,4,1,0,0,0,0,1,0],[2,1,3,2,4,1,0,0,0,0,0,1]])
print(a)

[[1 1 1 2 1 2 1 0 0 0 0 0]
 [2 3 1 1 4 2 0 1 0 0 0 0]
 [1 3 2 2 4 1 0 0 1 0 0 0]
 [1 1 1 1 1 1 0 0 0 1 0 0]
 [3 3 3 2 4 1 0 0 0 0 1 0]
 [2 1 3 2 4 1 0 0 0 0 0 1]]


In [12]:
b = RowAdd(a,3,0,-1)
print(b)

[[ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 2.  3.  1.  1.  4.  2.  0.  1.  0.  0.  0.  0.]
 [ 1.  3.  2.  2.  4.  1.  0.  0.  1.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  0.  0.]
 [ 3.  3.  3.  2.  4.  1.  0.  0.  0.  0.  1.  0.]
 [ 2.  1.  3.  2.  4.  1.  0.  0.  0.  0.  0.  1.]]


In [13]:
c = RowAdd(b,1,4,-1)
print(c)

[[ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 2.  3.  1.  1.  4.  2.  0.  1.  0.  0.  0.  0.]
 [ 1.  3.  2.  2.  4.  1.  0.  0.  1.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  0.  0.]
 [ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 2.  1.  3.  2.  4.  1.  0.  0.  0.  0.  0.  1.]]


In [14]:
d = RowSwap(c,4,0)
print(d)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 2.  3.  1.  1.  4.  2.  0.  1.  0.  0.  0.  0.]
 [ 1.  3.  2.  2.  4.  1.  0.  0.  1.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 2.  1.  3.  2.  4.  1.  0.  0.  0.  0.  0.  1.]]


In [15]:
e = RowSwap(d,4,3)
print(e)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 2.  3.  1.  1.  4.  2.  0.  1.  0.  0.  0.  0.]
 [ 1.  3.  2.  2.  4.  1.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  0.  0.]
 [ 2.  1.  3.  2.  4.  1.  0.  0.  0.  0.  0.  1.]]


In [16]:
f = RowAdd(e,3,1,-2)
print(f)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 2.  3.  1. -1.  4.  0. -2.  1.  0.  2.  0.  0.]
 [ 1.  3.  2.  2.  4.  1.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  0.  0.]
 [ 2.  1.  3.  2.  4.  1.  0.  0.  0.  0.  0.  1.]]


In [17]:
g = RowAdd(f,3,4,-1)
print(g)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 2.  3.  1. -1.  4.  0. -2.  1.  0.  2.  0.  0.]
 [ 1.  3.  2.  2.  4.  1.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  0.  1.  0. -1.  0.  0.  2.  0.  0.]
 [ 2.  1.  3.  2.  4.  1.  0.  0.  0.  0.  0.  1.]]


In [18]:
h = RowAdd(g,4,1,-2)
print(h)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1.  2.  0.  0.  1.  0. -2.  0.  0.]
 [ 1.  3.  2.  2.  4.  1.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  0.  1.  0. -1.  0.  0.  2.  0.  0.]
 [ 2.  1.  3.  2.  4.  1.  0.  0.  0.  0.  0.  1.]]


In [19]:
i = RowAdd(h,4,2,-1)
print(i)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1.  2.  0.  0.  1.  0. -2.  0.  0.]
 [ 0.  2.  1.  2.  3.  1.  1.  0.  1. -2.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  0.  1.  0. -1.  0.  0.  2.  0.  0.]
 [ 2.  1.  3.  2.  4.  1.  0.  0.  0.  0.  0.  1.]]


In [20]:
j = RowAdd(i,0,5,-1)
print(j)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1.  2.  0.  0.  1.  0. -2.  0.  0.]
 [ 0.  2.  1.  2.  3.  1.  1.  0.  1. -2.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  0.  1.  0. -1.  0.  0.  2.  0.  0.]
 [ 1.  1.  1.  1.  4.  2.  0.  1.  0.  0. -1.  1.]]


In [21]:
k = RowAdd(j,3,5,-1)
print(k)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1.  2.  0.  0.  1.  0. -2.  0.  0.]
 [ 0.  2.  1.  2.  3.  1.  1.  0.  1. -2.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  0.  1.  0. -1.  0.  0.  2.  0.  0.]
 [ 1.  1.  1.  0.  4.  1. -1.  1.  0.  1. -1.  1.]]


In [22]:
l = RowAdd(k,4,5,-1)
print(l)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1.  2.  0.  0.  1.  0. -2.  0.  0.]
 [ 0.  2.  1.  2.  3.  1.  1.  0.  1. -2.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  0.  1.  0. -1.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  3.  1.  0.  1.  0. -1. -1.  1.]]


In [23]:
m = RowAdd(l,5,2,-1)
print(m)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1.  2.  0.  0.  1.  0. -2.  0.  0.]
 [ 0.  2.  1.  2.  0.  0.  1. -1.  1. -1.  1. -1.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  0.  1.  0. -1.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  3.  1.  0.  1.  0. -1. -1.  1.]]


In [24]:
n = RowAdd(m,5,1,-1)
print(n)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1. -1. -1.  0.  0.  0. -1.  1. -1.]
 [ 0.  2.  1.  2.  0.  0.  1. -1.  1. -1.  1. -1.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 1.  1.  1.  0.  1.  0. -1.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  3.  1.  0.  1.  0. -1. -1.  1.]]


In [25]:
o = RowAdd(n,0,4,-1)
print(o)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1. -1. -1.  0.  0.  0. -1.  1. -1.]
 [ 0.  2.  1.  2.  0.  0.  1. -1.  1. -1.  1. -1.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 0.  1. -1. -1.  1.  1. -1.  1.  0.  2. -1.  0.]
 [ 0.  0.  0.  0.  3.  1.  0.  1.  0. -1. -1.  1.]]


In [26]:
p = RowAdd(o,1,4,-1)
print(p)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1. -1. -1.  0.  0.  0. -1.  1. -1.]
 [ 0.  2.  1.  2.  0.  0.  1. -1.  1. -1.  1. -1.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  2.  2. -1.  1.  0.  3. -2.  1.]
 [ 0.  0.  0.  0.  3.  1.  0.  1.  0. -1. -1.  1.]]


In [27]:
q = RowAdd(p,1,2,-2)
print(q)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1. -1. -1.  0.  0.  0. -1.  1. -1.]
 [ 0.  0.  3.  4.  2.  2.  1. -1.  1.  1. -1.  1.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  2.  2. -1.  1.  0.  3. -2.  1.]
 [ 0.  0.  0.  0.  3.  1.  0.  1.  0. -1. -1.  1.]]


In [28]:
r = RowScale(q,5,2)
print(r)

[[ 1.  0.  2.  1.  0. -1.  0. -1.  0.  0.  1.  0.]
 [ 0.  1. -1. -1. -1. -1.  0.  0.  0. -1.  1. -1.]
 [ 0.  0.  3.  4.  2.  2.  1. -1.  1.  1. -1.  1.]
 [ 0.  0.  0.  1.  0.  1.  1.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  2.  2. -1.  1.  0.  3. -2.  1.]
 [ 0.  0.  0.  0.  6.  2.  0.  2.  0. -2. -2.  2.]]


In [29]:
s = RowAdd(r,4,5,-3)
print(s)

[[  1.   0.   2.   1.   0.  -1.   0.  -1.   0.   0.   1.   0.]
 [  0.   1.  -1.  -1.  -1.  -1.   0.   0.   0.  -1.   1.  -1.]
 [  0.   0.   3.   4.   2.   2.   1.  -1.   1.   1.  -1.   1.]
 [  0.   0.   0.   1.   0.   1.   1.   0.   0.  -1.   0.   0.]
 [  0.   0.   0.   0.   2.   2.  -1.   1.   0.   3.  -2.   1.]
 [  0.   0.   0.   0.   0.  -4.   3.  -1.   0. -11.   4.  -1.]]


In [30]:
t = RowScale(s,5,-1/4)
print(t)

[[ 1.    0.    2.    1.    0.   -1.    0.   -1.    0.    0.    1.    0.  ]
 [ 0.    1.   -1.   -1.   -1.   -1.    0.    0.    0.   -1.    1.   -1.  ]
 [ 0.    0.    3.    4.    2.    2.    1.   -1.    1.    1.   -1.    1.  ]
 [ 0.    0.    0.    1.    0.    1.    1.    0.    0.   -1.    0.    0.  ]
 [ 0.    0.    0.    0.    2.    2.   -1.    1.    0.    3.   -2.    1.  ]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [31]:
u = RowAdd(t,5,0,1)
print(u)

[[ 1.    0.    2.    1.    0.    0.   -0.75 -0.75  0.    2.75  0.    0.25]
 [ 0.    1.   -1.   -1.   -1.   -1.    0.    0.    0.   -1.    1.   -1.  ]
 [ 0.    0.    3.    4.    2.    2.    1.   -1.    1.    1.   -1.    1.  ]
 [ 0.    0.    0.    1.    0.    1.    1.    0.    0.   -1.    0.    0.  ]
 [ 0.    0.    0.    0.    2.    2.   -1.    1.    0.    3.   -2.    1.  ]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [32]:
v = RowAdd(u,5,3,-1)
print(v)

[[ 1.    0.    2.    1.    0.    0.   -0.75 -0.75  0.    2.75  0.    0.25]
 [ 0.    1.   -1.   -1.   -1.   -1.    0.    0.    0.   -1.    1.   -1.  ]
 [ 0.    0.    3.    4.    2.    2.    1.   -1.    1.    1.   -1.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    2.    2.   -1.    1.    0.    3.   -2.    1.  ]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [33]:
w = RowAdd(v,4,2,-1)
print(w)

[[ 1.    0.    2.    1.    0.    0.   -0.75 -0.75  0.    2.75  0.    0.25]
 [ 0.    1.   -1.   -1.   -1.   -1.    0.    0.    0.   -1.    1.   -1.  ]
 [ 0.    0.    3.    4.    0.    0.    2.   -2.    1.   -2.    1.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    2.    2.   -1.    1.    0.    3.   -2.    1.  ]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [34]:
x = RowAdd(w,5,1,1)
print(x)

[[ 1.    0.    2.    1.    0.    0.   -0.75 -0.75  0.    2.75  0.    0.25]
 [ 0.    1.   -1.   -1.   -1.    0.   -0.75  0.25  0.    1.75  0.   -0.75]
 [ 0.    0.    3.    4.    0.    0.    2.   -2.    1.   -2.    1.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    2.    2.   -1.    1.    0.    3.   -2.    1.  ]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [35]:
y = RowAdd(x,3,1,1)
print(y)

[[ 1.    0.    2.    1.    0.    0.   -0.75 -0.75  0.    2.75  0.    0.25]
 [ 0.    1.   -1.    0.   -1.    0.    1.    0.    0.   -2.    1.   -1.  ]
 [ 0.    0.    3.    4.    0.    0.    2.   -2.    1.   -2.    1.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    2.    2.   -1.    1.    0.    3.   -2.    1.  ]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [36]:
z = RowAdd(y,3,2,-4)
print(z)

[[ 1.    0.    2.    1.    0.    0.   -0.75 -0.75  0.    2.75  0.    0.25]
 [ 0.    1.   -1.    0.   -1.    0.    1.    0.    0.   -2.    1.   -1.  ]
 [ 0.    0.    3.    0.    0.    0.   -5.   -1.    1.   13.   -3.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    2.    2.   -1.    1.    0.    3.   -2.    1.  ]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [37]:
a = RowAdd(z,3,0,-1)
print(a)

[[ 1.    0.    2.    0.    0.    0.   -2.5  -0.5   0.    6.5  -1.    0.5 ]
 [ 0.    1.   -1.    0.   -1.    0.    1.    0.    0.   -2.    1.   -1.  ]
 [ 0.    0.    3.    0.    0.    0.   -5.   -1.    1.   13.   -3.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    2.    2.   -1.    1.    0.    3.   -2.    1.  ]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [38]:
b = RowAdd(a,5,4,-2)
print(b)

[[ 1.    0.    2.    0.    0.    0.   -2.5  -0.5   0.    6.5  -1.    0.5 ]
 [ 0.    1.   -1.    0.   -1.    0.    1.    0.    0.   -2.    1.   -1.  ]
 [ 0.    0.    3.    0.    0.    0.   -5.   -1.    1.   13.   -3.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    2.    0.    0.5   0.5   0.   -2.5   0.    0.5 ]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [39]:
c = RowScale(b,4,1/2)
print(c)

[[ 1.    0.    2.    0.    0.    0.   -2.5  -0.5   0.    6.5  -1.    0.5 ]
 [ 0.    1.   -1.    0.   -1.    0.    1.    0.    0.   -2.    1.   -1.  ]
 [ 0.    0.    3.    0.    0.    0.   -5.   -1.    1.   13.   -3.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    1.    0.    0.25  0.25  0.   -1.25  0.    0.25]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [40]:
d = RowAdd(c,4,1,1)
print(d)

[[ 1.    0.    2.    0.    0.    0.   -2.5  -0.5   0.    6.5  -1.    0.5 ]
 [ 0.    1.   -1.    0.    0.    0.    1.25  0.25  0.   -3.25  1.   -0.75]
 [ 0.    0.    3.    0.    0.    0.   -5.   -1.    1.   13.   -3.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    1.    0.    0.25  0.25  0.   -1.25  0.    0.25]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [41]:
e = RowAdd(d,1,0,2)
print(e)

[[ 1.    2.    0.    0.    0.    0.    0.    0.    0.    0.    1.   -1.  ]
 [ 0.    1.   -1.    0.    0.    0.    1.25  0.25  0.   -3.25  1.   -0.75]
 [ 0.    0.    3.    0.    0.    0.   -5.   -1.    1.   13.   -3.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    1.    0.    0.25  0.25  0.   -1.25  0.    0.25]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [42]:
f = RowAdd(e,1,0,-2)
print(f)

[[ 1.    0.    2.    0.    0.    0.   -2.5  -0.5   0.    6.5  -1.    0.5 ]
 [ 0.    1.   -1.    0.    0.    0.    1.25  0.25  0.   -3.25  1.   -0.75]
 [ 0.    0.    3.    0.    0.    0.   -5.   -1.    1.   13.   -3.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    1.    0.    0.25  0.25  0.   -1.25  0.    0.25]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [43]:
g = RowAdd(f,2,0,-1)
print(g)

[[ 1.    0.   -1.    0.    0.    0.    2.5   0.5  -1.   -6.5   2.   -0.5 ]
 [ 0.    1.   -1.    0.    0.    0.    1.25  0.25  0.   -3.25  1.   -0.75]
 [ 0.    0.    3.    0.    0.    0.   -5.   -1.    1.   13.   -3.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    1.    0.    0.25  0.25  0.   -1.25  0.    0.25]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [44]:
h = RowAdd(g,0,1,-1)
print(h)

[[ 1.    0.   -1.    0.    0.    0.    2.5   0.5  -1.   -6.5   2.   -0.5 ]
 [-1.    1.    0.    0.    0.    0.   -1.25 -0.25  1.    3.25 -1.   -0.25]
 [ 0.    0.    3.    0.    0.    0.   -5.   -1.    1.   13.   -3.    1.  ]
 [ 0.    0.    0.    1.    0.    0.    1.75 -0.25  0.   -3.75  1.   -0.25]
 [ 0.    0.    0.    0.    1.    0.    0.25  0.25  0.   -1.25  0.    0.25]
 [-0.   -0.   -0.   -0.   -0.    1.   -0.75  0.25 -0.    2.75 -1.    0.25]]


In [45]:
i = RowScale(h,2,1/3)
print(i)

[[ 1.          0.         -1.          0.          0.          0.
   2.5         0.5        -1.         -6.5         2.         -0.5       ]
 [-1.          1.          0.          0.          0.          0.
  -1.25       -0.25        1.          3.25       -1.         -0.25      ]
 [ 0.          0.          1.          0.          0.          0.
  -1.66666667 -0.33333333  0.33333333  4.33333333 -1.          0.33333333]
 [ 0.          0.          0.          1.          0.          0.
   1.75       -0.25        0.         -3.75        1.         -0.25      ]
 [ 0.          0.          0.          0.          1.          0.
   0.25        0.25        0.         -1.25        0.          0.25      ]
 [-0.         -0.         -0.         -0.         -0.          1.
  -0.75        0.25       -0.          2.75       -1.          0.25      ]]


In [46]:
j = RowAdd(i,2,0,1)
print(j)

[[ 1.          0.          0.          0.          0.          0.
   0.83333333  0.16666667 -0.66666667 -2.16666667  1.         -0.16666667]
 [-1.          1.          0.          0.          0.          0.
  -1.25       -0.25        1.          3.25       -1.         -0.25      ]
 [ 0.          0.          1.          0.          0.          0.
  -1.66666667 -0.33333333  0.33333333  4.33333333 -1.          0.33333333]
 [ 0.          0.          0.          1.          0.          0.
   1.75       -0.25        0.         -3.75        1.         -0.25      ]
 [ 0.          0.          0.          0.          1.          0.
   0.25        0.25        0.         -1.25        0.          0.25      ]
 [-0.         -0.         -0.         -0.         -0.          1.
  -0.75        0.25       -0.          2.75       -1.          0.25      ]]


In [47]:
k = RowAdd(j,0,1,1)
print(k)

[[ 1.          0.          0.          0.          0.          0.
   0.83333333  0.16666667 -0.66666667 -2.16666667  1.         -0.16666667]
 [ 0.          1.          0.          0.          0.          0.
  -0.41666667 -0.08333333  0.33333333  1.08333333  0.         -0.41666667]
 [ 0.          0.          1.          0.          0.          0.
  -1.66666667 -0.33333333  0.33333333  4.33333333 -1.          0.33333333]
 [ 0.          0.          0.          1.          0.          0.
   1.75       -0.25        0.         -3.75        1.         -0.25      ]
 [ 0.          0.          0.          0.          1.          0.
   0.25        0.25        0.         -1.25        0.          0.25      ]
 [-0.         -0.         -0.         -0.         -0.          1.
  -0.75        0.25       -0.          2.75       -1.          0.25      ]]


In [48]:
hasil = np.array([[0.83,0.16,-0.6,-2.1,1,-0.16],[-0.416,-0.083,0.3,1.083,0,-0.416],[-1.6,-0.3,0.3,4.3,-1,0.3],[1.75,-0.25,0,-3.75,1,-0.25],[0.25,0.25,0,-1.25,0,0.25],[ -0.75,0.25,-0,2.75,-1,0.25]])
print(hasil)
kons= np.array([[14],[23],[21],[11],[29],[22]])
print("Pembuktian \n",hasil@kons)

[[ 0.83   0.16  -0.6   -2.1    1.    -0.16 ]
 [-0.416 -0.083  0.3    1.083  0.    -0.416]
 [-1.6   -0.3    0.3    4.3   -1.     0.3  ]
 [ 1.75  -0.25   0.    -3.75   1.    -0.25 ]
 [ 0.25   0.25   0.    -1.25   0.     0.25 ]
 [-0.75   0.25   0.     2.75  -1.     0.25 ]]
Pembuktian 
 [[5.08 ]
 [1.328]
 [1.9  ]
 [1.   ]
 [1.   ]
 [2.   ]]


In [49]:
mat1 = np.array([[1,1,1,2,1,2],[2,3,1,1,4,2],[1,3,2,2,4,1],[1,1,1,1,1,1],[3,3,3,2,4,1,],[2,1,3,2,4,1]])
print(mat1)

[[1 1 1 2 1 2]
 [2 3 1 1 4 2]
 [1 3 2 2 4 1]
 [1 1 1 1 1 1]
 [3 3 3 2 4 1]
 [2 1 3 2 4 1]]


In [50]:
mtrx= np. array([[0.83333333,0.16666667,-0.66666667,-2.16666667,1,-0.16666667],[-0.41666667,-0.08333333,0.33333333,1.08333333,0,-0.41666667],[-1.66666667,-0.33333333,0.33333333,4.33333333,-1,0.33333333],[1.75,-0.25,0,-3.75,1,-0.25],[0.25,0.25,0,-1.25,0,0.25],[ -0.75,0.25,-0,2.75,-1,0.25]])
print(mtrx)

[[ 0.83333333  0.16666667 -0.66666667 -2.16666667  1.         -0.16666667]
 [-0.41666667 -0.08333333  0.33333333  1.08333333  0.         -0.41666667]
 [-1.66666667 -0.33333333  0.33333333  4.33333333 -1.          0.33333333]
 [ 1.75       -0.25        0.         -3.75        1.         -0.25      ]
 [ 0.25        0.25        0.         -1.25        0.          0.25      ]
 [-0.75        0.25        0.          2.75       -1.          0.25      ]]


In [51]:
# mtrx.round()
print(mtrx.round())

[[ 1.  0. -1. -2.  1. -0.]
 [-0. -0.  0.  1.  0. -0.]
 [-2. -0.  0.  4. -1.  0.]
 [ 2. -0.  0. -4.  1. -0.]
 [ 0.  0.  0. -1.  0.  0.]
 [-1.  0.  0.  3. -1.  0.]]


In [52]:
h = mtrx@mat1
print(h.round())

[[ 1. -0. -0. -0. -0. -0.]
 [-0.  1. -0. -0. -0. -0.]
 [-0. -0.  1. -0. -0. -0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


In [55]:
print((mtrx@h).round())

[[ 1.  0. -1. -2.  1. -0.]
 [-0. -0.  0.  1.  0. -0.]
 [-2. -0.  0.  4. -1.  0.]
 [ 2. -0. -0. -4.  1. -0.]
 [ 0.  0. -0. -1. -0.  0.]
 [-1.  0.  0.  3. -1.  0.]]


In [53]:
kons= np.array([[14],[23],[21],[11],[29],[22]])
hk= mtrx@kons
print(hk.round())

[[3.]
 [2.]
 [2.]
 [1.]
 [1.]
 [2.]]
