# Tugas 2
Tidak mengerjakan diluar

## Aljabar Matrix

- Berikan penjelasan tentang apa itu matrix
- Operasi Matrix
  - Penjumlahan
  - Pengurangan
  - Perkalian
  - Transpose Matrix
- Buat program untuk mengalikan matrix A dan B tanpa menggunakan "@"

Matrix adalah suatu kumpulan bilangan sejumlah m x n yang disusun menjadi m adalah baris dan n adalah kolom

Matrix terdiri dari beberapa jenis diantaranya adalah
- matrix persegi
- matrix kolom
- matrix baris
- matrix Transpose
- matrix diagonal
- matrix simetri
- matrix segitiga atas dan segitiga bawah
- matrix nol
- matrix identitas

In [1]:
# saya disuruh mebuat matrik A (3x3) B (3x3) C (3x2)
#

import numpy as np
A=np.array([[8,9,1],[1,2,3],[2,1,1]])
print("a\n", A)

B=np.array([[2,1,9],[4,3,2],[3,4,4]])
print("b\n", B)

C=np.array([[3,3],[1,2],[2,1]])
print("c\n", C)

a
 [[8 9 1]
 [1 2 3]
 [2 1 1]]
b
 [[2 1 9]
 [4 3 2]
 [3 4 4]]
c
 [[3 3]
 [1 2]
 [2 1]]


In [4]:
# Penjumlahan
D = A+B
print("Matrix D adalah perkalian dari Matrix A dan B\n",D)

Matrix D adalah perkalian dari Matrix A dan B
 [[10 10 10]
 [ 5  5  5]
 [ 5  5  5]]


In [5]:
# Perkalian
E = A@B
F = B@C
print("Matrix E adalah hasil perkalian dari Matrix A dan B \n", E)
print("Matrix F adalah hasil perkalian dari Matrix B dan C \n", F)
print("-"*30)
# Perkalian Lainnya
print(A@(B@C))

print((A@B)@C)
print("-"*30)
print(7*(A@B))
print((7*A)@B)
print(A@(7*B))
print("-"*30)

Matrix E adalah hasil perkalian dari Matrix A dan B 
 [[55 39 94]
 [19 19 25]
 [11  9 24]]
Matrix F adalah hasil perkalian dari Matrix B dan C 
 [[25 17]
 [19 20]
 [21 21]]
------------------------------
[[392 337]
 [126 120]
 [ 90  75]]
[[392 337]
 [126 120]
 [ 90  75]]
------------------------------
[[385 273 658]
 [133 133 175]
 [ 77  63 168]]
[[385 273 658]
 [133 133 175]
 [ 77  63 168]]
[[385 273 658]
 [133 133 175]
 [ 77  63 168]]
------------------------------


In [7]:
C_T= C.transpose()
print("Matrix C Transpose\n",C_T)
print("-"*30)
print("Matrix C Transpose dikali dengan Matrix C\n", C_T@C)
print("-"*30)
print("Matrix C dikali dengan Matrix C Transpose\n", C@C_T)

Matrix C Transpose
 [[3 1 2]
 [3 2 1]]
------------------------------
Matrix C Transpose dikali dengan Matrix C
 [[14 13]
 [13 14]]
------------------------------
Matrix C dikali dengan Matrix C Transpose
 [[18  9  9]
 [ 9  5  4]
 [ 9  4  5]]


In [11]:
# Manual operasi perkalian matrix
m1 = [[8,9,1],
            [1,2,3],
            [2,1,1]]

m2 = [[2,1,9],
            [4,3,2],
            [3,4,4]]
Result = []

def multiply_matrix(matrix1,matrix2):
  result = [[0,0,0],[0,0,0],[0,0,0]] # Menginisialisasikan dulu matrix dengan semua value 0

  for i in range(len(m1)):
    for j in range(len(m2[0])):
      for k in range(len(m2)):
        result[i][j] += m1[i][k] * m2[k][j]
  return result

hasil = multiply_matrix(m1,m2)
print()
print(f"Hasil perkalian Matrix_1 dan Matrix 2 = {hasil}")
print()
print(f"Pembuktian untuk Matrix A @ B =\n{A @ B}")


Hasil perkalian Matrix_1 dan Matrix 2 = [[55, 39, 94], [19, 19, 25], [11, 9, 24]]

Pembuktian untuk Matrix A @ B =
[[55 39 94]
 [19 19 25]
 [11  9 24]]
