## Aljabar Matrix
Matrix adalah suatu kumpulan bilangan real yang disusun dengan bentuk m x n yang dimana m itu adalah baris dan n kolom

pada matrix terdapat beberapa elemen matrix yang terdapat pada suatu bangun matrix, Contoh: Jika menggunkan varibel A $$ [[a_11], [a_1,2], [dst]]$$

### Matrix terdiri dari beberapa jenis diantaranya adalah
- matrix persegi
- matrix kolom
- matrix baris
- matrix Transpose
- matrix diagonal
- matrix simetri
- matrix segitiga atas dan segitiga bawah
- matrix nol
- matrix identitas

### Operasi Matrix
Penjumlahan Matrix

Pada penjumlahan matrix,syarat dari penjulahan matrix adalah kedua bangun matrix harus memiliki jumlah kolom dan baris yang sama, agar dapat dijumlahkan satu sama lain semisal Matrix A (3,3) + B (3,3), A (2,3) + B (2,3)
jika suatu bangun matrix tidak memiliki jumlah kolom dan baris yang tidak sama maka matrix tidak dapat dijumlahkan karena ada beberapa elemen matrix yang tidak memiliki pasangan






In [1]:
# saya disuruh mebuat matrik A (3x3) B (3x3) C (3x2)
#

import numpy as np
A=np.array ([[0.2,0.1,-0.7],[-0.2,0.4,0.2],[0.2,-0.4,0.8]])
print("a\n", A)

B=np.array([[4,2,3],[2,3,1],[0,1,1]])
print("b\n", B)

C=np.array([[3,3],[1,2],[2,1]])
print("c\n", C)

a
 [[ 0.2  0.1 -0.7]
 [-0.2  0.4  0.2]
 [ 0.2 -0.4  0.8]]
b
 [[4 2 3]
 [2 3 1]
 [0 1 1]]
c
 [[3 3]
 [1 2]
 [2 1]]


In [2]:
# Penjumlahan
D = A+B
print("Matrix D adalah perkalian dari Matrix A dan B\n",D)

Matrix D adalah perkalian dari Matrix A dan B
 [[10 10 10]
 [ 5  5  5]
 [ 5  5  5]]


Pengurangan

Konsep pada pengurangan matrix sama dengan penjulahan dimana setiap elemen matrix harus memiliki pasangan agar dapat dioperasikan, setelah dua buah matrix dioperasikan maka akan menghasilkan matrix baru yang elemennya terdiri dari hasil pengurangan elemen elemen matrix yang teroperasi

In [3]:
Z = A - B
print("Matrix Z adalah contoh dari hasil pengurangan MAtrix A, dan Matrix B\n", Z)

Matrix Z adalah contoh dari hasil pengurangan MAtrix A, dan Matrix B
 [[ 6  8 -8]
 [-3 -1  1]
 [-1 -3 -3]]


Perkalian
- Perkalian matrix dengan skalar
operasi ini dilakukan dengan cara mengalikan setiap elemen matrix dengan skalar tersebut, yang kemudian akan menghsilkan ssebuah matrix baru
, Contoh operasi matrix skalar adalah Matrix A x 7 maka operasi yang akan diproses adalah setiap elemen pada matrix A x 7

- Perkalian matrix dengan matrix
dapat diasumsikan bahwasannya jika semisal matrix A x matrix B maka kolom dari Matrix A harus sama dengan baris Matrix. contoh operasinya adalah
elemen dari matrix A [(a,b)] matrix B [(c,d)] = [(ac + bd)]

In [4]:
# Perkalian
E = A@B
F = B@A

print("a \n",A)
print("b\n", B)
print("Matrix E adalah hasil perkalian dari Matrix A dan B \n", E.arrow)
print("Matrix F adalah hasil perkalian dari Matrix B dan C \n", F)
print("-"*30)
# Perkalian Lainnya
print(A@(B@C))

print((A@B)@C)
print("-"*30)
print(7*(A@B))
print((7*A)@B)
print(A@(7*B))
print("-"*30)

a 
 [[ 0.2  0.1 -0.7]
 [-0.2  0.4  0.2]
 [ 0.2 -0.4  0.8]]
b
 [[4 2 3]
 [2 3 1]
 [0 1 1]]


TypeError: type numpy.ndarray doesn't define __round__ method

Transpose

Transpose dari sebuah matrix adalah operator yang membalikkan posisi matrix sepanjang diagonal utamanya dalam kata lain menukarkan antara baris dan kolomnya

In [ ]:
C_T= C.transpose()
print("Matrix C Transpose\n",C_T)
print("-"*30)
print("Matrix C Transpose dikali dengan Matrix C\n", C_T@C)
print("-"*30)
print("Matrix C dikali dengan Matrix C Transpose\n", C@C_T)

Matrix C Transpose
 [[3 1 2]
 [3 2 1]]
------------------------------
Matrix C Transpose dikali dengan Matrix C
 [[14 13]
 [13 14]]
------------------------------
Matrix C dikali dengan Matrix C Transpose
 [[18  9  9]
 [ 9  5  4]
 [ 9  4  5]]


In [6]:
# Manual operasi perkalian matrix
m1 = [[1,4],
            [-1,-3]]

m2 = [[3,4],
            [-1,-1]]
Result = []

def multiply_matrix(matrix1,matrix2):
  result = [[0,0],[0,0]] # Menginisialisasikan dulu matrix dengan semua value 0

  for i in range(len(m1)):
    for j in range(len(m2)):
      for k in range(len(m2)):
        result[i][j] += m1[i][k] * m2[k][j]
  return result

hasil = multiply_matrix(m1,m2)
print(f"Hasil perkalian Matrix_1 dan Matrix 2 = {hasil}")
print(f"Pembuktian untuk Matrix A @ B =\n{A @ B}")

Hasil perkalian Matrix_1 dan Matrix 2 = [[-1, 0], [0, -1]]
Pembuktian untuk Matrix A @ B =
[[55 39 94]
 [19 19 25]
 [11  9 24]]
