# Tugas 2
Tidak mengerjakan diluar

## Aljabar Matrix

- Berikan penjelasan tentang apa itu matrix
Operasi Matrix

Matrix adalah larik dalam dua dimensi

In [5]:
# saya disuruh mebuat matrik A (3x3) B (3x3) C (3x2)
#

import numpy as np
A=np.array([[8,9,1],[1,2,3],[2,1,1]])
print("a\n", A)

B=np.array([[2,1,9],[4,3,2],[3,4,4]])
print("b\n", B)

C=np.array([[3,3],[1,2],[2,1]])
print("c\n", C)

D=np.array([[1,1,5],[4,3,2],[3,2,4]])
print("d\n", D)

a
 [[8 9 1]
 [1 2 3]
 [2 1 1]]
b
 [[2 1 9]
 [4 3 2]
 [3 4 4]]
c
 [[3 3]
 [1 2]
 [2 1]]
d
 [[1 1 5]
 [4 3 2]
 [3 2 4]]


In [6]:
import numpy as np
A=np.array([[8,9,1],[1,2,3],[2,1,1]])
print("a\n", A)
print()

B=np.array([[2,1,9],[4,3,2],[3,4,4]])
print("b\n", B)
print()
print( "E=\n", A+B )

print("F=\n", 2*A)
print("G=\n", A@C)

a
 [[8 9 1]
 [1 2 3]
 [2 1 1]]

b
 [[2 1 9]
 [4 3 2]
 [3 4 4]]

E=
 [[10 10 10]
 [ 5  5  5]
 [ 5  5  5]]
F=
 [[16 18  2]
 [ 2  4  6]
 [ 4  2  2]]
G=
 [[35 43]
 [11 10]
 [ 9  9]]


In [7]:
print(A@(B@C))

print((A@B)@C)
print("-"*30)
print(7*(A@B))
print((7*A)@B)
print(A@(7*B))
print("-"*30)

[[392 337]
 [126 120]
 [ 90  75]]
[[392 337]
 [126 120]
 [ 90  75]]
------------------------------
[[385 273 658]
 [133 133 175]
 [ 77  63 168]]
[[385 273 658]
 [133 133 175]
 [ 77  63 168]]
[[385 273 658]
 [133 133 175]
 [ 77  63 168]]
------------------------------


In [9]:
C= np.array([[3,3],[1,2],[2,1]])
print("c\n", C)
C_T= C.transpose()
print(C_T)
print("-"*30)
print(C_T@C)
print("-"*30)
print(C@C_T)

c
 [[3 3]
 [1 2]
 [2 1]]
[[3 1 2]
 [3 2 1]]
------------------------------
[[14 13]
 [13 14]]
------------------------------
[[18  9  9]
 [ 9  5  4]
 [ 9  4  5]]
